@startuml
' --- PRETTIER STYLING ---
skinparam actor {
    BackgroundColor White
    BorderColor Black
}
skinparam usecase {
    BackgroundColor White
    BorderColor #222
}
skinparam PackageStyle rectangle
left to right direction

' --- ACTORS ---
actor "Guest" as G 
actor "User" as U

' --- SYSTEM BOUNDARY ---
rectangle "Sassy Me (Rate My Life)"#Physical {
    
    package "Identity"#business {
        usecase "Log In" as L 
        usecase "Manage Profile" as MP 
    }

    package "Content Management"#business {
        usecase "Create New Post" as NP 
        usecase "Mark as Favorite" as FAV 
    }

    package "Social"#business  {
        usecase "View FYP (Feed)" as SF 
        usecase "Filter Feed by Tags" as FF  
        usecase "Comment on Post" as CP 
        usecase "Add Friends" as AF 
    }
}

' --- CONNECTIONS ---
G -- L
G <|-- U
U -- MP
U -- NP
U -- SF
U -- FF
U -- CP
U -- AF
U -- FAV

@enduml