@startuml domainmodel

class User {
  id: Long
  username: String
  password: String
  email: String
  bio: String
  profilePicture: String
  isPublic: boolean
  createdAt: Date
  updatedAt: Date
}

class Post {
  id: Long
  title: String
  image: String
  date: Date
  rating: int
  createdAt: Date
  updatedAt: Date
}

class Comment {
  id: Long
  content: String
  createdAt: Date
  updatedAt: Date
}

enum TagType {
  BOOKS
  CLOTHES
  FOOD
  GAMES
  CONCERTS
  ALBUMS
  THEATRE
  BATHROOM
  DISASTERS
  OH_NO
  CINEMA_MOVIES
  MUSIC
  VIDEOGAMES
}

class Tag {
  id: Long
  name: String
  type: TagType
  color: String
}

class Favorite {
  id: Long
  createdAt: Date
}

class Follow {
  id: Long
  createdAt: Date
}

class Feed {
  id: Long
  visibility: String
  createdAt: Date
}

class Profile {
  id: Long
  displayName: String
  location: String
  website: String
  joinDate: Date
}

' Relationships

User "1" -- "1" Profile : has > 
User "1" -- "*" Post : creates >
User "1" -- "*" Comment : writes >
User "1" -- "*" Favorite : creates  >
User "*" -- "*" User : followed_by >

Follow "*" -- "1" User : follower >
Follow "*" -- "1" User : followed_by >

Post "1" -- "*" Comment : has >
Post "*" --"*" Tag : tagged_with >
Post "1" -- "1" Favorite : of_post >

Comment "*"--"1" User : written_by >
Comment "*" -- "1" Post : belongs_to >

Feed "1" -- "*" Post : contains >
Feed "1" -- "1" User : belongs_to >

Tag "*" -- "1" TagType : categorized_as >

@enduml
